Hm4
bushev1970/EPAM_Traning pull request #4
Opened 2018-04-09 15:10 UTC by bushev1970

2018-04-09 15:22 UTC, thebesson commented
![image](https://user-images.githubusercontent.com/12238477/38506612-06f029a0-3c23-11e8-8e0f-05862866e0fe.png)

2018-04-09 15:23 UTC, thebesson requested changes
к странице не подключены стили

2018-04-09 15:29 UTC, bushev1970 commented
Так. И как нам  это исправить?)) Ведь в link все подключено  <link rel="stylesheet" type="text/css" href="style/style.css">
Может дело в том что я в sass писал?



>Понедельник,  9 апреля 2018, 18:23 +03:00 от thebesson <notifications@github.com>:
>
>@thebesson requested changes on this pull request.
>к странице не подключены стили
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

2018-04-09 15:56 UTC, thebesson commented
Ну не знаю как ты это будешь исправлять, начнем с того что ты подключаешь несуществующий файл style.css. :)

2018-04-11 09:07 UTC, thebesson approved these changes

2018-04-12 05:07 UTC, merged